name: Provide Secrets Only

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:   # botón manual en la pestaña Actions

jobs:
  setup-secrets:
    runs-on: ubuntu-latest

    env:
      GRAPH__CLIENTID: ${{ secrets.GRAPH__CLIENTID }}
      GRAPH__CLIENTSECRET: ${{ secrets.GRAPH__CLIENTSECRET }}
      GRAPH__TENANTID: ${{ secrets.GRAPH__TENANTID }}

    steps:
      - name: Show that secrets are available (sanity check)
        run: |
          echo "Secrets loaded into environment."
          echo "GRAPH__CLIENTID length: ${#GRAPH__CLIENTID}"
          echo "GRAPH__TENANTID: ${GRAPH__TENANTID}"
          # ⚠️ nunca hagas echo del ClientSecret completo
